import { GatePaperInfo, GateSource, GateEvent, GateUpdate, GateSyllabusTopic, GateResource } from './gateTypes';

export const GATE_2027_OFFICIAL_URL = 'https://gate2027.iitm.ac.in/';
export const GATE_LAST_VERIFIED_DATE = '2026-09-25T12:00:00Z';

export const GATE_PAPERS: GatePaperInfo[] = [
  {
    code: 'CSE',
    name: 'Computer Science & Information Technology',
    category: 'Computer & Data Science',
    isFullySupported: true,
    description: 'Core GATE paper for CS & IT graduates covering Data Structures, Algorithms, OS, DBMS, Networks, TOC, Compilers, Architecture & Math.',
    totalMarks: 100,
    totalQuestions: 65,
    durationMinutes: 180,
    allowedSecondPapers: ['DA'],
    officialSyllabusUrl: `${GATE_2027_OFFICIAL_URL}syllabus/cse`,
  },
  {
    code: 'DA',
    name: 'Data Science & Artificial Intelligence',
    category: 'Computer & Data Science',
    isFullySupported: true,
    description: 'Newer GATE paper focusing on Probability, Statistics, Linear Algebra, Machine Learning, AI Search Algorithms & Data Warehousing.',
    totalMarks: 100,
    totalQuestions: 65,
    durationMinutes: 180,
    allowedSecondPapers: ['CSE', 'ECE', 'ST', 'MA'],
    officialSyllabusUrl: `${GATE_2027_OFFICIAL_URL}syllabus/da`,
  },
  {
    code: 'ECE',
    name: 'Electronics & Communication Engineering',
    category: 'Electrical & Electronics',
    isFullySupported: true,
    description: 'Paper covering Network Theory, Signals & Systems, Electronic Devices, Analog/Digital Circuits, Control Systems & Communications.',
    totalMarks: 100,
    totalQuestions: 65,
    durationMinutes: 180,
    allowedSecondPapers: ['EE', 'IN', 'CSE'],
    officialSyllabusUrl: `${GATE_2027_OFFICIAL_URL}syllabus/ece`,
  },
  {
    code: 'EE',
    name: 'Electrical Engineering',
    category: 'Electrical & Electronics',
    isFullySupported: true,
    description: 'Paper covering Electric Circuits, Electromagnetic Fields, Signals, Electrical Machines, Power Systems & Power Electronics.',
    totalMarks: 100,
    totalQuestions: 65,
    durationMinutes: 180,
    allowedSecondPapers: ['ECE', 'IN'],
    officialSyllabusUrl: `${GATE_2027_OFFICIAL_URL}syllabus/ee`,
  },
  {
    code: 'ME',
    name: 'Mechanical Engineering',
    category: 'Mechanical & Civil',
    isFullySupported: true,
    description: 'Paper covering Engineering Mechanics, Strength of Materials, Thermodynamics, Fluid Mechanics & Manufacturing Engineering.',
    totalMarks: 100,
    totalQuestions: 65,
    durationMinutes: 180,
    allowedSecondPapers: ['XE', 'PI'],
    officialSyllabusUrl: `${GATE_2027_OFFICIAL_URL}syllabus/me`,
  },
  {
    code: 'CE',
    name: 'Civil Engineering',
    category: 'Mechanical & Civil',
    isFullySupported: true,
    description: 'Paper covering Structural Engineering, Geotechnical Engineering, Water Resources, Environmental & Transportation Engineering.',
    totalMarks: 100,
    totalQuestions: 65,
    durationMinutes: 180,
    allowedSecondPapers: ['AR', 'ES'],
    officialSyllabusUrl: `${GATE_2027_OFFICIAL_URL}syllabus/ce`,
  },
  {
    code: 'CH',
    name: 'Chemical Engineering',
    category: 'Process & Bio Sciences',
    isFullySupported: false,
    description: 'Paper covering Process Calculations, Thermodynamics, Fluid Mechanics, Heat Transfer, Mass Transfer & Reaction Engineering.',
    totalMarks: 100,
    totalQuestions: 65,
    durationMinutes: 180,
    allowedSecondPapers: ['PE', 'XE'],
    officialSyllabusUrl: `${GATE_2027_OFFICIAL_URL}syllabus/ch`,
  },
  {
    code: 'BT',
    name: 'Biotechnology',
    category: 'Process & Bio Sciences',
    isFullySupported: false,
    description: 'Paper covering Microbiology, Biochemistry, Molecular Biology, Recombinant DNA Tech, Bioprocess Engineering & Bioinformatics.',
    totalMarks: 100,
    totalQuestions: 65,
    durationMinutes: 180,
    allowedSecondPapers: ['XL', 'BM'],
    officialSyllabusUrl: `${GATE_2027_OFFICIAL_URL}syllabus/bt`,
  },
  {
    code: 'IN',
    name: 'Instrumentation Engineering',
    category: 'Electrical & Electronics',
    isFullySupported: false,
    description: 'Paper covering Sensors, Transducers, Industrial Instrumentation, Signals, Control Systems & Analog Circuits.',
    totalMarks: 100,
    totalQuestions: 65,
    durationMinutes: 180,
    allowedSecondPapers: ['ECE', 'EE'],
    officialSyllabusUrl: `${GATE_2027_OFFICIAL_URL}syllabus/in`,
  },
];

export const GATE_SOURCES: GateSource[] = [
  {
    id: 'src_gate_official',
    name: 'Official GATE 2027 Portal (Organizing IIT Madras)',
    url: GATE_2027_OFFICIAL_URL,
    sourceType: 'official',
    isOfficial: true,
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
  },
  {
    id: 'src_nptel',
    name: 'NPTEL (National Programme on Technology Enhanced Learning)',
    url: 'https://nptel.ac.in/',
    sourceType: 'institutional',
    isOfficial: false,
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
  },
  {
    id: 'src_mit_ocw',
    name: 'MIT OpenCourseWare (Engineering & Computer Science)',
    url: 'https://ocw.mit.edu/',
    sourceType: 'educational',
    isOfficial: false,
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
  },
];

export const GATE_EVENTS: GateEvent[] = [
  {
    id: 'evt_reg_start',
    examYear: 2027,
    title: 'GATE 2027 Registration Window Opens',
    eventType: 'registration',
    startDate: '2026-09-02T00:00:00Z',
    endDate: '2026-09-27T23:59:59Z',
    dateLabel: '02 Sep 2026',
    status: 'completed',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'evt_reg_regular',
    examYear: 2027,
    title: 'Regular Registration Deadline (Without Late Fee)',
    eventType: 'registration',
    startDate: '2026-09-27T00:00:00Z',
    endDate: '2026-09-27T23:59:59Z',
    dateLabel: '27 Sep 2026',
    status: 'ongoing',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'evt_reg_extended',
    examYear: 2027,
    title: 'Extended Registration Deadline (With Late Fee)',
    eventType: 'registration',
    startDate: '2026-09-28T00:00:00Z',
    endDate: '2026-10-05T23:59:59Z',
    dateLabel: '05 Oct 2026',
    status: 'upcoming',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'evt_correction',
    examYear: 2027,
    title: 'Application Rectification Window',
    eventType: 'correction',
    startDate: '2026-10-14T00:00:00Z',
    endDate: '2026-10-21T23:59:59Z',
    dateLabel: '14–21 Oct 2026',
    status: 'upcoming',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'evt_admit_card',
    examYear: 2027,
    title: 'City Allotment Notification & Admit Card Release',
    eventType: 'admit_card',
    startDate: '2027-01-04T00:00:00Z',
    dateLabel: '04 Jan 2027',
    status: 'upcoming',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'evt_exam_days',
    examYear: 2027,
    title: 'GATE 2027 Examinations',
    eventType: 'exam',
    startDate: '2027-02-06T00:00:00Z',
    endDate: '2027-02-21T23:59:59Z',
    dateLabel: '06–21 Feb 2027 (Feb 6, 7, 13, 14 & 20, 21)',
    status: 'upcoming',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'evt_results',
    examYear: 2027,
    title: 'GATE 2027 Official Results Announcement',
    eventType: 'result',
    startDate: '2027-03-19T00:00:00Z',
    dateLabel: '19 Mar 2027',
    status: 'upcoming',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
];

export const GATE_UPDATES: GateUpdate[] = [
  {
    id: 'upd_2027_01',
    examYear: 2027,
    title: 'DigiLocker Integration Update for Document Verification',
    summary: 'The GATE 2027 organizing committee updated instructions regarding category certificate and degree verification via DigiLocker for streamlined document processing.',
    whatItMeans: 'Candidates with DigiLocker linked identity & degree documents can complete application verification faster with reduced manual audit holds.',
    updateType: 'guidelines_update',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    publishedAt: '2026-09-19T09:00:00Z',
    detectedAt: '2026-09-19T09:30:00Z',
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'upd_2027_02',
    examYear: 2027,
    title: 'Candidate Photograph & Signature Upload Specifications',
    summary: 'Clarification issued on background color, resolution, and facial capture constraints for photo submission during GATE 2027 registration.',
    whatItMeans: 'Avoid white/overexposed background photos to prevent rejection during the rectification window (14-21 Oct 2026).',
    updateType: 'official_announcement',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    publishedAt: '2026-09-17T14:00:00Z',
    detectedAt: '2026-09-17T14:15:00Z',
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'upd_2027_03',
    examYear: 2027,
    title: 'PwD Candidate Facial Capture Assistance Update',
    summary: 'Special assistance measures published for facial biometric capture and scribe allocation procedures at exam centers.',
    whatItMeans: 'PwD candidates requiring scribes or assistive devices can submit requests via GOAPS before the extended deadline.',
    updateType: 'guidelines_update',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    publishedAt: '2026-09-10T11:00:00Z',
    detectedAt: '2026-09-10T11:30:00Z',
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'upd_2027_04',
    examYear: 2027,
    title: 'GATE 2027 Official Notification & Website Launched',
    summary: 'The official GATE 2027 organizing institute (IIT Madras) released the formal exam notification, key dates schedule, and information brochure.',
    whatItMeans: 'All candidates can access verified 2027 paper codes, syllabus structures, and fee schedules directly on the official portal.',
    updateType: 'official_announcement',
    sourceId: 'src_gate_official',
    officialUrl: GATE_2027_OFFICIAL_URL,
    publishedAt: '2026-08-28T08:00:00Z',
    detectedAt: '2026-08-28T08:30:00Z',
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
];

export const GATE_CSE_SYLLABUS: GateSyllabusTopic[] = [
  {
    id: 'cse_os_deadlocks',
    examYear: 2027,
    paperCode: 'CSE',
    paperName: 'Computer Science & Information Technology',
    subjectId: 'os',
    subjectName: 'Operating Systems',
    subjectOrder: 1,
    topicId: 'deadlocks',
    topicName: 'Process Deadlocks & Resource Allocation',
    topicOrder: 1,
    subtopics: [
      'Necessary and Sufficient Conditions for Deadlock',
      'Resource Allocation Graph (RAG)',
      'Deadlock Handling Strategies',
      'Banker\'s Algorithm for Deadlock Avoidance',
      'Deadlock Detection and Recovery Algorithms'
    ],
    weightageEstimate: '3 – 5% of GATE CSE exam paper',
    conceptSummary: 'A deadlock occurs when a set of processes are blocked because each process holds a resource and waits for another resource held by some other process in the set.',
    whyItMatters: 'Deadlocks test core concepts of concurrency, state safety, and resource tracking. Numerical problems on Banker\'s Algorithm and minimum resource requirements appear consistently in GATE CSE.',
    keyTakeaways: [
      'Master the 4 conditions: Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait',
      'Know how to compute Safe Sequence using Banker\'s Algorithm matrices (Max, Allocation, Need, Available)',
      'Understand single vs multi-instance resource graph reduction techniques'
    ],
    version: '2027',
    sourceId: 'src_gate_official',
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
  },
  {
    id: 'cse_os_sync',
    examYear: 2027,
    paperCode: 'CSE',
    paperName: 'Computer Science & Information Technology',
    subjectId: 'os',
    subjectName: 'Operating Systems',
    subjectOrder: 1,
    topicId: 'process_sync',
    topicName: 'Process Synchronization & Semaphores',
    topicOrder: 2,
    subtopics: [
      'Critical Section Problem & Requirements',
      'Peterson\'s Solution & Hardware Locks',
      'Counting & Binary Semaphores',
      'Producer-Consumer & Bounded Buffer Problem',
      'Readers-Writers & Dining Philosophers Problems'
    ],
    weightageEstimate: '4 – 6% of GATE CSE exam paper',
    conceptSummary: 'Process synchronization ensures safe execution of concurrent processes sharing memory space, preventing race conditions using atomic hardware and software primitives.',
    whyItMatters: 'GATE questions frequently involve analyzing pseudo-code with semaphores to determine mutual exclusion violations, deadlocks, or progress guarantees.',
    keyTakeaways: [
      'Verify 3 critical section requirements: Mutual Exclusion, Progress, Bounded Waiting',
      'Calculate semaphore values after series of P() / wait() and V() / signal() operations',
      'Identify race conditions in shared variable updates'
    ],
    version: '2027',
    sourceId: 'src_gate_official',
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
  },
  {
    id: 'cse_algo_dp',
    examYear: 2027,
    paperCode: 'CSE',
    paperName: 'Computer Science & Information Technology',
    subjectId: 'algo',
    subjectName: 'Algorithms',
    subjectOrder: 2,
    topicId: 'dynamic_programming',
    topicName: 'Dynamic Programming & Recurrence Relations',
    topicOrder: 1,
    subtopics: [
      'Optimal Substructure & Overlapping Subproblems',
      '0/1 Knapsack Problem & Subset Sum',
      'Longest Common Subsequence (LCS)',
      'Matrix Chain Multiplication',
      'Bellman-Ford & All-Pairs Shortest Path (Floyd-Warshall)'
    ],
    weightageEstimate: '5 – 7% of GATE CSE exam paper',
    conceptSummary: 'Dynamic Programming solves complex optimization problems by breaking them down into simpler subproblems and storing subproblem results in memoization tables.',
    whyItMatters: 'DP recurrence equations and table state transitions form the backbone of GATE algorithm weightage.',
    keyTakeaways: [
      'Formulate time and space complexities from DP state transition formulas',
      'Differentiate top-down memoization from bottom-up tabulation',
      'Recognize subproblem dependencies in 1D and 2D DP matrices'
    ],
    version: '2027',
    sourceId: 'src_gate_official',
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
  },
  {
    id: 'cse_dbms_norm',
    examYear: 2027,
    paperCode: 'CSE',
    paperName: 'Computer Science & Information Technology',
    subjectId: 'dbms',
    subjectName: 'Databases (DBMS)',
    subjectOrder: 3,
    topicId: 'normalization',
    topicName: 'Functional Dependencies & Normalization',
    topicOrder: 1,
    subtopics: [
      'Functional Dependency Closure & Attribute Closure',
      'Candidate Key Determination',
      '1NF, 2NF, 3NF & BCNF Definitions',
      'Lossless Join Decomposition Check',
      'Dependency Preserving Decomposition'
    ],
    weightageEstimate: '4 – 6% of GATE CSE exam paper',
    conceptSummary: 'Normalization decomposes relational schemas to eliminate redundancy and update anomalies while preserving functional dependencies and lossless join constraints.',
    whyItMatters: 'Questions asking "What is the highest normal form of relation R?" or checking lossless decomposition are guaranteed numerical scoring opportunities.',
    keyTakeaways: [
      'Find all candidate keys using attribute closure set algorithm',
      'Verify BCNF condition: For X -> Y, X must be a superkey',
      'Check lossless join condition: (R1 ∩ R2) -> R1 or (R1 ∩ R2) -> R2'
    ],
    version: '2027',
    sourceId: 'src_gate_official',
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
  },
  {
    id: 'cse_cn_tcp',
    examYear: 2027,
    paperCode: 'CSE',
    paperName: 'Computer Science & Information Technology',
    subjectId: 'cn',
    subjectName: 'Computer Networks',
    subjectOrder: 4,
    topicId: 'tcp_ip',
    topicName: 'Transport Layer & TCP Congestion Control',
    topicOrder: 1,
    subtopics: [
      'TCP 3-Way Handshake & Connection Teardown',
      'TCP Header Fields & Sequence/ACK Numbers',
      'Sliding Window Protocol & Throughput Math',
      'Slow Start, Congestion Avoidance, Fast Retransmit',
      'UDP vs TCP Mechanics'
    ],
    weightageEstimate: '4 – 6% of GATE CSE exam paper',
    conceptSummary: 'TCP provides reliable, ordered, byte-stream delivery with flow control and congestion window scaling across unreliable networks.',
    whyItMatters: 'Calculating TCP congestion window size changes across rounds and maximum achievable throughput based on RTT are common GATE numericals.',
    keyTakeaways: [
      'Track Congestion Window (cwnd) doubling during Slow Start vs linear increment during Congestion Avoidance',
      'Calculate threshold (ssthresh) reduction upon timeout vs 3 duplicate ACKs',
      'Compute window efficiency = Sender Window / (1 + 2 * (Propagation Delay / Transmission Delay))'
    ],
    version: '2027',
    sourceId: 'src_gate_official',
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
  }
];

export const GATE_RESOURCES: GateResource[] = [
  {
    id: 'res_os_dl_01',
    examYear: 2027,
    topicId: 'deadlocks',
    title: 'Operating Systems — Banker\'s Algorithm & Deadlock Avoidance',
    resourceType: 'video',
    provider: 'NPTEL / IIT Madras (Prof. P.C. P. Bhatt)',
    url: 'https://nptel.ac.in/courses/106106144',
    description: 'Rigorous academic lecture explaining single and multi-resource safety checks with step-by-step Banker\'s algorithm walkthrough.',
    isPrimary: true,
    sourceClassification: 'curated_learning',
    sourceId: 'src_nptel',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_os_dl_02',
    examYear: 2027,
    topicId: 'deadlocks',
    title: 'Operating System Concepts — Chapter 8: Deadlocks',
    resourceType: 'textbook',
    provider: 'Silberschatz, Galvin & Gagne (Standard Text)',
    url: 'https://www.os-book.com/',
    description: 'Standard textbook chapter covering deadlock prevention, avoidance, detection, and resource allocation graph reductions.',
    isPrimary: true,
    sourceClassification: 'curated_learning',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_os_dl_pyq',
    examYear: 2027,
    topicId: 'deadlocks',
    title: 'Official GATE CSE Deadlock Previous Year Questions',
    resourceType: 'pyq',
    provider: 'Official GATE Committee PYQ Repository',
    url: GATE_2027_OFFICIAL_URL,
    description: 'Collection of verified GATE questions on Deadlocks with complete step-by-step matrix solutions.',
    isPrimary: true,
    sourceClassification: 'official_source',
    sourceId: 'src_gate_official',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_os_dl_03',
    examYear: 2027,
    topicId: 'deadlocks',
    title: 'MIT OCW Operating Systems Lecture Notes — Concurrency & Deadlock',
    resourceType: 'notes',
    provider: 'MIT OpenCourseWare (6.004)',
    url: 'https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/',
    description: 'Concise lecture notes summarizing state graphs, deadlock conditions, and dining philosopher solutions.',
    isPrimary: false,
    sourceClassification: 'external_resource',
    sourceId: 'src_mit_ocw',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_os_sync_01',
    examYear: 2027,
    topicId: 'process_sync',
    title: 'Process Synchronization & Semaphores Lecture Series',
    resourceType: 'video',
    provider: 'NPTEL / IIT Kharagpur',
    url: 'https://nptel.ac.in/courses/106105214',
    description: 'In-depth explanation of hardware atomic primitives (TestAndSet), Peterson\'s algorithm, and semaphore implementations.',
    isPrimary: true,
    sourceClassification: 'curated_learning',
    sourceId: 'src_nptel',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_os_sync_pyq',
    examYear: 2027,
    topicId: 'process_sync',
    title: 'Official GATE CSE Process Synchronization PYQs',
    resourceType: 'pyq',
    provider: 'Official GATE Committee PYQ Repository',
    url: GATE_2027_OFFICIAL_URL,
    description: 'GATE questions on critical section code analysis, counting semaphores, and concurrency traps.',
    isPrimary: true,
    sourceClassification: 'official_source',
    sourceId: 'src_gate_official',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_algo_dp_01',
    examYear: 2027,
    topicId: 'dynamic_programming',
    title: 'Design & Analysis of Algorithms — Dynamic Programming Module',
    resourceType: 'video',
    provider: 'NPTEL / IIT Delhi',
    url: 'https://nptel.ac.in/courses/106102011',
    description: 'Rigorous mathematical derivation of DP state recurrences for Knapsack, LCS, and Matrix Chain Multiplication.',
    isPrimary: true,
    sourceClassification: 'curated_learning',
    sourceId: 'src_nptel',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_algo_dp_pyq',
    examYear: 2027,
    topicId: 'dynamic_programming',
    title: 'Official GATE CSE Algorithms & DP Previous Questions',
    resourceType: 'pyq',
    provider: 'Official GATE Committee PYQ Repository',
    url: GATE_2027_OFFICIAL_URL,
    description: 'Step-by-step solved GATE questions on recurrence relations and DP table size calculations.',
    isPrimary: true,
    sourceClassification: 'official_source',
    sourceId: 'src_gate_official',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_db_norm_01',
    examYear: 2027,
    topicId: 'normalization',
    title: 'Database Systems — Relational Normalization & Functional Dependencies',
    resourceType: 'video',
    provider: 'NPTEL / IIT Bombay',
    url: 'https://nptel.ac.in/courses/106101060',
    description: 'Comprehensive guide to computing attribute closure sets, canonical covers, and BCNF/3NF decompositions.',
    isPrimary: true,
    sourceClassification: 'curated_learning',
    sourceId: 'src_nptel',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_db_norm_pyq',
    examYear: 2027,
    topicId: 'normalization',
    title: 'Official GATE CSE DBMS Normalization PYQs',
    resourceType: 'pyq',
    provider: 'Official GATE Committee PYQ Repository',
    url: GATE_2027_OFFICIAL_URL,
    description: 'GATE questions testing normal form identification, candidate key counts, and lossless join proofs.',
    isPrimary: true,
    sourceClassification: 'official_source',
    sourceId: 'src_gate_official',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_cn_tcp_01',
    examYear: 2027,
    topicId: 'tcp_ip',
    title: 'Computer Networks — Transport Layer & Congestion Control',
    resourceType: 'video',
    provider: 'NPTEL / IIT Kharagpur',
    url: 'https://nptel.ac.in/courses/106105081',
    description: 'Detailed analysis of TCP header fields, 3-way handshake sequence math, and congestion window growth curves.',
    isPrimary: true,
    sourceClassification: 'curated_learning',
    sourceId: 'src_nptel',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  },
  {
    id: 'res_cn_tcp_pyq',
    examYear: 2027,
    topicId: 'tcp_ip',
    title: 'Official GATE CSE Computer Networks TCP PYQs',
    resourceType: 'pyq',
    provider: 'Official GATE Committee PYQ Repository',
    url: GATE_2027_OFFICIAL_URL,
    description: 'GATE questions on TCP throughput, window size calculations, and fast retransmit state transitions.',
    isPrimary: true,
    sourceClassification: 'official_source',
    sourceId: 'src_gate_official',
    lastCheckedAt: GATE_LAST_VERIFIED_DATE,
    lastVerifiedAt: GATE_LAST_VERIFIED_DATE,
    verificationStatus: 'verified',
  }
];
