import { supabase } from "@/integrations/supabase/client";

// Local type definitions for the new Career Intelligence schema
// These will eventually be generated by Supabase CLI

export interface CareerCompany {
  id: string;
  name: string;
  industry: string | null;
  company_type: string | null;
  product_service: string | null;
  tech_stack: string[];
  hiring_pattern: string | null;
  interview_rounds: number | null;
  difficulty: string | null;
  salary_range: string | null;
  benefits: string[];
  hiring_frequency: string | null;
  locations: string[];
  career_growth: string | null;
  careers_link: string | null;
  source: string | null;
  last_updated: string | null;
  confidence_score: number | null;
  verification_status: string | null;
  created_at: string;
}

export interface RoleInformation {
  id: string;
  title: string;
  overview: string | null;
  responsibilities: string[];
  daily_work: string | null;
  required_skills: string[];
  preferred_skills: string[];
  languages: string[];
  frameworks: string[];
  cloud: string[];
  tools: string[];
  expected_experience: string | null;
  promotion_path: string | null;
  salary_progression: any;
  future_demand: string | null;
  automation_risk: string | null;
  learning_resources: any;
  companies_hiring: string[];
  source: string | null;
  last_updated: string | null;
  confidence_score: number | null;
  verification_status: string | null;
  created_at: string;
}

export interface SkillMaster {
  id: string;
  name: string;
  description: string | null;
  difficulty: string | null;
  learning_time: string | null;
  projects: any;
  companies_using: string[];
  interview_questions: any;
  related_roles: string[];
}

export interface SkillRelationship {
  id: string;
  skill_id: string;
  prerequisite_skill_id: string;
  relationship_type: string | null;
}

export interface CareerPath {
  id: string;
  start_role: string;
  target_role: string;
  steps: any;
}

export interface ExperiencePath {
  id: string;
  target_company: string;
  target_role: string;
  starter_companies: string[];
  experience_duration: string | null;
  promotion_path: any;
  intermediate_companies: string[];
}

// ------------------------------------------------------------------
// Career Intelligence Service
// Provides read-only access to the Career Knowledge Layer
// ------------------------------------------------------------------

export const CareerIntelligenceService = {
  // Company Intelligence (Phase 3)
  async getCompany(companyId: string): Promise<CareerCompany | null> {
    const { data, error } = await supabase
      .from("companies")
      .select("*")
      .eq("id", companyId)
      .maybeSingle();

    if (error) {
      console.error("Error fetching company intelligence:", error);
      return null;
    }
    return data as CareerCompany | null;
  },

  async searchCompanies(query: string): Promise<CareerCompany[]> {
    const { data, error } = await supabase
      .from("companies")
      .select("*")
      .ilike("name", `%${query}%`)
      .limit(10);
      
    if (error) return [];
    return data as CareerCompany[];
  },

  // Role Intelligence (Phase 4)
  async getRole(roleId: string): Promise<RoleInformation | null> {
    const { data, error } = await supabase
      .from("role_information")
      .select("*")
      .eq("id", roleId)
      .maybeSingle();

    if (error) {
      console.error("Error fetching role intelligence:", error);
      return null;
    }
    return data as RoleInformation | null;
  },

  async searchRoles(query: string): Promise<RoleInformation[]> {
    const { data, error } = await supabase
      .from("role_information")
      .select("*")
      .ilike("title", `%${query}%`)
      .limit(10);
      
    if (error) return [];
    return data as RoleInformation[];
  },

  // Skill Intelligence (Phase 5)
  async getSkillGraph(skillId: string): Promise<{ skill: SkillMaster, prerequisites: SkillMaster[] } | null> {
    const { data: skill, error: skillError } = await supabase
      .from("skills_master")
      .select("*")
      .eq("id", skillId)
      .maybeSingle();
      
    if (skillError || !skill) return null;

    const { data: relationships } = await supabase
      .from("skill_relationships")
      .select("prerequisite_skill_id")
      .eq("skill_id", skillId);

    let prerequisites: SkillMaster[] = [];
    if (relationships && relationships.length > 0) {
      const prereqIds = relationships.map((r: any) => r.prerequisite_skill_id);
      const { data: prereqData } = await supabase
        .from("skills_master")
        .select("*")
        .in("id", prereqIds);
      if (prereqData) prerequisites = prereqData as SkillMaster[];
    }

    return { skill: skill as SkillMaster, prerequisites };
  },

  // Experience Bridge (Phase 9)
  async getExperiencePath(targetCompany: string, targetRole: string): Promise<ExperiencePath | null> {
    const { data, error } = await supabase
      .from("experience_paths")
      .select("*")
      .eq("target_company", targetCompany)
      .eq("target_role", targetRole)
      .maybeSingle();

    if (error) {
      console.error("Error fetching experience path:", error);
      return null;
    }
    return data as ExperiencePath | null;
  }
};
