/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CareerTransformationsRouteImport } from './routes/career-transformations'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUpdatePasswordRouteImport } from './routes/_authenticated/update-password'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResumeIntelligenceRouteImport } from './routes/_authenticated/resume-intelligence'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDsaRoadmapRouteImport } from './routes/_authenticated/dsa-roadmap'
import { Route as AuthenticatedDsaProblemsRouteImport } from './routes/_authenticated/dsa-problems'
import { Route as AuthenticatedDsaMentorRouteImport } from './routes/_authenticated/dsa-mentor'
import { Route as AuthenticatedDsaDailyRouteImport } from './routes/_authenticated/dsa-daily'
import { Route as AuthenticatedDsaCompaniesRouteImport } from './routes/_authenticated/dsa-companies'
import { Route as AuthenticatedCareerIdentityRouteImport } from './routes/_authenticated/career-identity'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardWorkspaceRouteImport } from './routes/_authenticated/dashboard.workspace'
import { Route as AuthenticatedDashboardDsaRouteImport } from './routes/_authenticated/dashboard/dsa'

const CareerTransformationsRoute = CareerTransformationsRouteImport.update({
  id: '/career-transformations',
  path: '/career-transformations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpdatePasswordRoute =
  AuthenticatedUpdatePasswordRouteImport.update({
    id: '/update-password',
    path: '/update-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeIntelligenceRoute =
  AuthenticatedResumeIntelligenceRouteImport.update({
    id: '/resume-intelligence',
    path: '/resume-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDsaRoadmapRoute = AuthenticatedDsaRoadmapRouteImport.update({
  id: '/dsa-roadmap',
  path: '/dsa-roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDsaProblemsRoute =
  AuthenticatedDsaProblemsRouteImport.update({
    id: '/dsa-problems',
    path: '/dsa-problems',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDsaMentorRoute = AuthenticatedDsaMentorRouteImport.update({
  id: '/dsa-mentor',
  path: '/dsa-mentor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDsaDailyRoute = AuthenticatedDsaDailyRouteImport.update({
  id: '/dsa-daily',
  path: '/dsa-daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDsaCompaniesRoute =
  AuthenticatedDsaCompaniesRouteImport.update({
    id: '/dsa-companies',
    path: '/dsa-companies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCareerIdentityRoute =
  AuthenticatedCareerIdentityRouteImport.update({
    id: '/career-identity',
    path: '/career-identity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardWorkspaceRoute =
  AuthenticatedDashboardWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardDsaRoute =
  AuthenticatedDashboardDsaRouteImport.update({
    id: '/dsa',
    path: '/dsa',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/career-transformations': typeof CareerTransformationsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/career-identity': typeof AuthenticatedCareerIdentityRoute
  '/dsa-companies': typeof AuthenticatedDsaCompaniesRoute
  '/dsa-daily': typeof AuthenticatedDsaDailyRoute
  '/dsa-mentor': typeof AuthenticatedDsaMentorRoute
  '/dsa-problems': typeof AuthenticatedDsaProblemsRoute
  '/dsa-roadmap': typeof AuthenticatedDsaRoadmapRoute
  '/help': typeof AuthenticatedHelpRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resume-intelligence': typeof AuthenticatedResumeIntelligenceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/update-password': typeof AuthenticatedUpdatePasswordRoute
  '/dashboard/dsa': typeof AuthenticatedDashboardDsaRoute
  '/dashboard/workspace': typeof AuthenticatedDashboardWorkspaceRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/career-transformations': typeof CareerTransformationsRoute
  '/career-identity': typeof AuthenticatedCareerIdentityRoute
  '/dsa-companies': typeof AuthenticatedDsaCompaniesRoute
  '/dsa-daily': typeof AuthenticatedDsaDailyRoute
  '/dsa-mentor': typeof AuthenticatedDsaMentorRoute
  '/dsa-problems': typeof AuthenticatedDsaProblemsRoute
  '/dsa-roadmap': typeof AuthenticatedDsaRoadmapRoute
  '/help': typeof AuthenticatedHelpRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resume-intelligence': typeof AuthenticatedResumeIntelligenceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/update-password': typeof AuthenticatedUpdatePasswordRoute
  '/dashboard/dsa': typeof AuthenticatedDashboardDsaRoute
  '/dashboard/workspace': typeof AuthenticatedDashboardWorkspaceRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/career-transformations': typeof CareerTransformationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/career-identity': typeof AuthenticatedCareerIdentityRoute
  '/_authenticated/dsa-companies': typeof AuthenticatedDsaCompaniesRoute
  '/_authenticated/dsa-daily': typeof AuthenticatedDsaDailyRoute
  '/_authenticated/dsa-mentor': typeof AuthenticatedDsaMentorRoute
  '/_authenticated/dsa-problems': typeof AuthenticatedDsaProblemsRoute
  '/_authenticated/dsa-roadmap': typeof AuthenticatedDsaRoadmapRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/resume-intelligence': typeof AuthenticatedResumeIntelligenceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/update-password': typeof AuthenticatedUpdatePasswordRoute
  '/_authenticated/dashboard/dsa': typeof AuthenticatedDashboardDsaRoute
  '/_authenticated/dashboard/workspace': typeof AuthenticatedDashboardWorkspaceRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/career-transformations'
    | '/dashboard'
    | '/career-identity'
    | '/dsa-companies'
    | '/dsa-daily'
    | '/dsa-mentor'
    | '/dsa-problems'
    | '/dsa-roadmap'
    | '/help'
    | '/onboarding'
    | '/profile'
    | '/resume-intelligence'
    | '/settings'
    | '/update-password'
    | '/dashboard/dsa'
    | '/dashboard/workspace'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/career-transformations'
    | '/career-identity'
    | '/dsa-companies'
    | '/dsa-daily'
    | '/dsa-mentor'
    | '/dsa-problems'
    | '/dsa-roadmap'
    | '/help'
    | '/onboarding'
    | '/profile'
    | '/resume-intelligence'
    | '/settings'
    | '/update-password'
    | '/dashboard/dsa'
    | '/dashboard/workspace'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/career-transformations'
    | '/_authenticated/dashboard'
    | '/_authenticated/career-identity'
    | '/_authenticated/dsa-companies'
    | '/_authenticated/dsa-daily'
    | '/_authenticated/dsa-mentor'
    | '/_authenticated/dsa-problems'
    | '/_authenticated/dsa-roadmap'
    | '/_authenticated/help'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/resume-intelligence'
    | '/_authenticated/settings'
    | '/_authenticated/update-password'
    | '/_authenticated/dashboard/dsa'
    | '/_authenticated/dashboard/workspace'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CareerTransformationsRoute: typeof CareerTransformationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/career-transformations': {
      id: '/career-transformations'
      path: '/career-transformations'
      fullPath: '/career-transformations'
      preLoaderRoute: typeof CareerTransformationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/update-password': {
      id: '/_authenticated/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof AuthenticatedUpdatePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-intelligence': {
      id: '/_authenticated/resume-intelligence'
      path: '/resume-intelligence'
      fullPath: '/resume-intelligence'
      preLoaderRoute: typeof AuthenticatedResumeIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dsa-roadmap': {
      id: '/_authenticated/dsa-roadmap'
      path: '/dsa-roadmap'
      fullPath: '/dsa-roadmap'
      preLoaderRoute: typeof AuthenticatedDsaRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dsa-problems': {
      id: '/_authenticated/dsa-problems'
      path: '/dsa-problems'
      fullPath: '/dsa-problems'
      preLoaderRoute: typeof AuthenticatedDsaProblemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dsa-mentor': {
      id: '/_authenticated/dsa-mentor'
      path: '/dsa-mentor'
      fullPath: '/dsa-mentor'
      preLoaderRoute: typeof AuthenticatedDsaMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dsa-daily': {
      id: '/_authenticated/dsa-daily'
      path: '/dsa-daily'
      fullPath: '/dsa-daily'
      preLoaderRoute: typeof AuthenticatedDsaDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dsa-companies': {
      id: '/_authenticated/dsa-companies'
      path: '/dsa-companies'
      fullPath: '/dsa-companies'
      preLoaderRoute: typeof AuthenticatedDsaCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career-identity': {
      id: '/_authenticated/career-identity'
      path: '/career-identity'
      fullPath: '/career-identity'
      preLoaderRoute: typeof AuthenticatedCareerIdentityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/workspace': {
      id: '/_authenticated/dashboard/workspace'
      path: '/workspace'
      fullPath: '/dashboard/workspace'
      preLoaderRoute: typeof AuthenticatedDashboardWorkspaceRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/dsa': {
      id: '/_authenticated/dashboard/dsa'
      path: '/dsa'
      fullPath: '/dashboard/dsa'
      preLoaderRoute: typeof AuthenticatedDashboardDsaRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardDsaRoute: typeof AuthenticatedDashboardDsaRoute
  AuthenticatedDashboardWorkspaceRoute: typeof AuthenticatedDashboardWorkspaceRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardDsaRoute: AuthenticatedDashboardDsaRoute,
    AuthenticatedDashboardWorkspaceRoute: AuthenticatedDashboardWorkspaceRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedCareerIdentityRoute: typeof AuthenticatedCareerIdentityRoute
  AuthenticatedDsaCompaniesRoute: typeof AuthenticatedDsaCompaniesRoute
  AuthenticatedDsaDailyRoute: typeof AuthenticatedDsaDailyRoute
  AuthenticatedDsaMentorRoute: typeof AuthenticatedDsaMentorRoute
  AuthenticatedDsaProblemsRoute: typeof AuthenticatedDsaProblemsRoute
  AuthenticatedDsaRoadmapRoute: typeof AuthenticatedDsaRoadmapRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResumeIntelligenceRoute: typeof AuthenticatedResumeIntelligenceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUpdatePasswordRoute: typeof AuthenticatedUpdatePasswordRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedCareerIdentityRoute: AuthenticatedCareerIdentityRoute,
  AuthenticatedDsaCompaniesRoute: AuthenticatedDsaCompaniesRoute,
  AuthenticatedDsaDailyRoute: AuthenticatedDsaDailyRoute,
  AuthenticatedDsaMentorRoute: AuthenticatedDsaMentorRoute,
  AuthenticatedDsaProblemsRoute: AuthenticatedDsaProblemsRoute,
  AuthenticatedDsaRoadmapRoute: AuthenticatedDsaRoadmapRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResumeIntelligenceRoute: AuthenticatedResumeIntelligenceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUpdatePasswordRoute: AuthenticatedUpdatePasswordRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CareerTransformationsRoute: CareerTransformationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
